sudo: false
language: node_js
node_js:
  - 8
before_install:
  - npm install codecov.io coveralls --save-dev
after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
before_deploy:
  - echo "before deploy..."
  - npm install
  - npm run build -- --copy-files
# - npm version patch
# deploy:
#   - provider: npm
#     email: farmin.f@gmail.com
#     skip_cleanup: true
#     on:
#       branch: master
#       tags: true
#     api_key:
#       secure: W9EGlV4iSFh3YkwSBfnHv7FsldrcnUPW0Eww+mbvDgApRgPwvV2YVJ126CEqZAV2DZ90AxXFYoiAKvNJpItPQCzMHDGqcg6Vp+FnzdhyYCcXWZYioceuIkneCDqoGXA6hiEIzXDnJGWVpgyjVtO44DcY7TnPPOG4FNFQI5/Xbj/BrV23Kyt2s7qp6N0cO7x1Bwz+noSKESL/wl3/YJFGXHxqjQbp50nmAkLo1ChlWI5GvB1URsgv4xdLwD+QGUN4uKVii7CWA1xKG1xGDti9Si0I+whMKU+j2JvSs3ilEJDx0w+gQ1vlYjlinZwDsaDMA0Ty3hgvZv71KBIhWHWRYldnv/qmeIB0SAFZc44ajX6ckCS8YTbx9jkqXEmTYvQEWvKYvS23IGdoqGoHqfGFHkw0aGmXBvkpANhk6M1EgArVkTLCggJiWinly8bmVOHG0HmPX8U/raoTjVi9kyLhlaNO2BFpWLj3kCOJCSVubnezLo3xSKmRqzYpkuLpUCkz5cDh085/QzMbYL5tfay1dBJeZuux94qsdALikemkFCvuNpcT4cIFFAQgZWYRPLj8TMnKd67XFB6ydHpBPVtHQrBYcFbWmxQ52PMcCm9hMDiribSgTQTEp+pb6W5R4aO8J2WNp2/VTnFfpJDBRl78BIstyQXmvqMVZu0s2G54J4c=

#   - provider: npm
#     email: farmin.f@gmail.com
#     skip_cleanup: true
#     tag: next
#     on:
#       branch: develop
#     api_key:
#       secure: W9EGlV4iSFh3YkwSBfnHv7FsldrcnUPW0Eww+mbvDgApRgPwvV2YVJ126CEqZAV2DZ90AxXFYoiAKvNJpItPQCzMHDGqcg6Vp+FnzdhyYCcXWZYioceuIkneCDqoGXA6hiEIzXDnJGWVpgyjVtO44DcY7TnPPOG4FNFQI5/Xbj/BrV23Kyt2s7qp6N0cO7x1Bwz+noSKESL/wl3/YJFGXHxqjQbp50nmAkLo1ChlWI5GvB1URsgv4xdLwD+QGUN4uKVii7CWA1xKG1xGDti9Si0I+whMKU+j2JvSs3ilEJDx0w+gQ1vlYjlinZwDsaDMA0Ty3hgvZv71KBIhWHWRYldnv/qmeIB0SAFZc44ajX6ckCS8YTbx9jkqXEmTYvQEWvKYvS23IGdoqGoHqfGFHkw0aGmXBvkpANhk6M1EgArVkTLCggJiWinly8bmVOHG0HmPX8U/raoTjVi9kyLhlaNO2BFpWLj3kCOJCSVubnezLo3xSKmRqzYpkuLpUCkz5cDh085/QzMbYL5tfay1dBJeZuux94qsdALikemkFCvuNpcT4cIFFAQgZWYRPLj8TMnKd67XFB6ydHpBPVtHQrBYcFbWmxQ52PMcCm9hMDiribSgTQTEp+pb6W5R4aO8J2WNp2/VTnFfpJDBRl78BIstyQXmvqMVZu0s2G54J4c=
